# Generated by Django 4.1.7 on 2024-01-19 14:47

import apiservice.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('archived', models.BooleanField(default=False)),
                ('preview', models.ImageField(null=True, upload_to=apiservice.models.service_preview_directory_path)),
            ],
        ),
    ]
